phrase:
  project_id: e267b05f4b02914060adf563de93d5ce
  push:
    sources:
      - file: ./<locale_name>.xlf
        params:
          file_format: xlf
          locale_id: en
          update_translations: true
          autotranslate: true
  pull:
    targets:
      - file: ./<locale_name>.xlf
        params:
          file_format: xlf
